config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #Putting this after the devise routes to give devise precedences
  resources :users, only: [:show, :index] do
    resources :events, only: [:index] # This will generate a route for showing events associated with a user
  end
  get 'events/index'

  resources :events do
    get 'show_attendance', on: :member
    resources :attendances, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :attendances, only: [:index]


  root 'events#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances


  scope :past, -> {where("date < ?",DateTime.now)}
  scope :future, -> {where("date > ?", DateTime.now)}
  scope :by_creator, ->(creator_id) { where(creator_id: creator_id) }
  scope :open_invite, -> {where(invite_only: [false,nil])}
  # .or(where(invite_only: nil))}
  scope :invite_only, -> {where(invite_only: true)}
  scope :attended_by_user, ->(user_id) {Event.where(id: Attendance.select(:attended_event_id).where(attendee_id: user_id))}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.where.not(invite_only: true)
               .or(Event.where(creator: current_user))
               .or(Event.where(id: Attendance.where(attendee_id: current_user.id).pluck(:attended_event_id)))
               .future.order(date: :asc)

    @user_attendances = current_user.attendances
                          .where(attended_event_id: @events.pluck(:id))
                          .index_by(&:attended_event_id)
  end

  def show
    @event = Event.find(params[:id])
    @user_attendance = current_user.attendances.find_by(attended_event_id: params[:id])
    @attendees = @event.attendances
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path, notice: "Event Successfully Created"
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if current_user.id == @event.user_id
      if @event.update(event_params)
        redirect_to root_path, notice: "Event Successfully Updated"
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to root_path, alert: "You are not authorized to update this event"
    end
  end

  def show_attendance
    @event = Event.find(params[:id])
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :invite_only)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="event-form-container">
  <h1>New Event</h1>
  <h2>for <%= current_user.name %></h2>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error" ) %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: @event, html: { class: "event-form" } do |form| %>
    <div class="form-group">
      <%= form.label :title, "Title" %>
      <%= form.text_field :title, placeholder: "Your Event Title" %>
    </div>
    <div class="form-group">
      <%= form.label :date, "Date and Time" %>
      <%= form.datetime_local_field :date %>
    </div>
    <div class="form-group">
      <%= form.label :location, "Location" %>
      <%= form.text_field :location, placeholder: "8th Street House" %>
    </div>
    <div class="form-group">
      <%= form.label :description, "Description" %>
      <%= form.text_field :description, placeholder: "A party!" %>
    </div>
    <div class="form-group">
      <%= form.label :invite_only, "Invite Only?" %>
      <div class="radio_input">
        <%= form.radio_button :invite_only, true %>
        <%= form.label :invite_only_yes, "Yes" %>
      </div>
      <div class="radio_input">
        <%= form.radio_button :invite_only, false %>
        <%= form.label :invite_only_no, "No" %>
      </div>
    </div>
    <%= form.submit "Create Event", class: "btn btn-primary" %>
  <% end %>
</div>
<%= link_to 'Back', :back %>

app/views/events/edit.html.erb
<% if current_user.id == @event.creator_id %>
  <%= render "form" %>
<% else %>
  <p>You are not authorized to edit this event.</p>
<% end %>

app/views/events/index.html.erb
<h1>All Upcoming Events</h1>
<% if @events.any? %>
  <% @events.each_with_index do |event, index| %>
    <% formatted_date=event.date.strftime("%A, %B %-d, %Y, at (%H:%M)") %>
    <div class='event-container'>
      <h3 class='event-title'>
        <%= event.title %>
      </h3>
      <h4 class="event-creator">Hosted by: <%=event.creator.name %>
      </h4>
      <h4 class='event-location'>Location: <%= event.location %>
      </h4>
      <h4 class='event-date'>Date: <%= formatted_date %>
      </h4>
      <h4 class="event-rsvp-status">RSVP Status: <%=
                        humanize_attendance_status(@user_attendances[event.id]&.status) || "No Status" %>
      </h4>
    </h4>
    <%= link_to "See Details" , event_path(event) %>
  </div>
<% end %>
<% end %>

app/views/events/new.html.erb
<%= render "form" %>

app/views/events/show.html.erb
<h1>
  <%= @event.creator.name%>'s Event
</h1>
<% formatted_date=@event.date.strftime("%A, %B %-d, %Y, at (%H:%M)") %>
<div class='event-container'>
  <h3 class='event-title'>
    <%= @event.title %>
  </h3>
</h4>
<h4 class='event-location'>Location: <%= @event.location %>
</h4>
<h4 class='event-date'>Date: <%= formatted_date %>
</h4>
<p class='event-description'>
  <%= @event.description %>
</p>
<%# if current_user.id == @event.creator_id%>
<% link_to "Edit Event" , edit_event_path(@event) %>
<%#end%>
<% if @user_attendance %>
  <p>RSVP Status: <%= humanize_attendance_status @user_attendance.status %>
  </p>
  <%= link_to 'Update RSVP' , edit_event_attendance_path(@event, @user_attendance) %>
<% else %>
  <%if current_user == @event.creator%>
    <%= link_to 'Invite Guests' , new_event_attendance_path(@event) %>
  <%else%>
    <%= link_to 'Add RSVP' , new_event_attendance_path(@event) %>
  <%end%>
<% end %>
<h3>link_to Attendees</h3>
<h4>Attending: <%=@event.attendances.by_status(0).count %></h4>
<h4>Maybe: <%=@event.attendances.by_status(2).count %></h4>
<h4>Declined: <%=@event.attendances.by_status(1).count %></h4>
<h4>Awaiting Response: <%=@event.attendances.where(status: nil).count %></h4>
<div><%= link_to 'View Attendance', show_attendance_event_path(@event) %></div>
<%= link_to 'Back', :back %>
</div>

app/views/events/show_attendance.html.erb
<% @event.attendances.order(status: :asc, updated_at: :desc).each do |attendance| %>
  <div>
    <h3><%= attendance.attendee.name %></h3>
    <p>Status: <%= humanize_attendance_status attendance.status %></p>
  </div>
<% end %>
<%= link_to "Back", :back %>