config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  #Putting this after the devise routes to give devise precedences
  resources :users, only: [:show, :index] do
    resources :events, only: [:index] # This will generate a route for showing events associated with a user
  end
  get 'events/index'

  resources :events do
    get 'show_attendance', on: :member
    resources :attendances, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :attendances, only: [:index]


  root 'events#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar">
  <ul class="navbar-nav">
    <li class="nav-item home-link">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <%if user_signed_in?%>
      <li>Hello, <%= current_user.name%></li>
    <%end%>
    <li class="nav-grouping">
      <% if user_signed_in? %>
        <%= link_to "Create Event", new_event_path, class: "nav-link" %>
        <%= link_to "Your Events", user_path(current_user), class: "nav-link" %>
        <%= link_to "Invited Events", attendances_path, class: "nav-link"%>
        <%= link_to "Edit User",  edit_user_registration_path(current_user), class: "nav-link" %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-button", id: "sign-out-button" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      <%end%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" , {"data-turbo-track": "reload" } %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if notice.present? && notice.is_a?(String) %>
      <p class="notice">
        <%= notice %>
      </p>
    <%end%>
    <% if alert.present? && alert.is_a?(String) %>
      <p class="alert">
        <%= alert %>
      </p>
    <%end%>
    <%= yield %>
  </body>
</html>